train:  
  ycb:
    # 26
    - 004_sugar_box # trackable
    - 008_pudding_box # trackable
    - 010_potted_meat_can # trackable
    - 012_strawberry
    - 013_apple
    - 014_lemon
    - 016_pear
    - 026_sponge
    - 002_master_chef_can # trackable
    - 015_peach
    - 018_plum
    - 024_bowl # trackable
    - 025_mug # trackable
    # - 029_plate
    - 030_fork
    - 032_knife
    - 033_spatula
    - 036_wood_block # trackable
    - 042_adjustable_wrench
    - 043_phillips_screwdriver
    - 050_medium_clamp
    - 052_extra_large_clamp # trackagle
    - 053_mini_soccer_ball
    - 054_softball
    - 057_racquetball
    - 058_golf_ball
    - 077_rubiks_cube
  conveni:
    #  24
    - xylitol
    - toppo
    - kinokonoyama
    - chip_star
    - chocoball
    - gogotea_straight
    - oi_ocha_350ml
    - calorie_mate_cheese
    - xylitol_7assort
    - cupnoodle_curry    
    - creap
    - ginger_tube
    - java_curry_chukara
    - kikkoman_soysauce_gennenn
    - kizami_aojiso_tube
    - canned_iwashi_kabayaki
    - pan_meat
    - vermont_curry_amakuchi
    - jif
    - 7i_handsoap
    - clinica_ad_hamigaki
    - clinica_advantage
    - nonio_strong_energy

test:
  ycb:
    # 18
    - 005_tomato_soup_can # trackable
    - 007_tuna_fish_can # trackable
    - 009_gelatin_box # trackable
    - 011_banana # trackable
    - 017_orange
    - 040_large_marker # trackable
    - 055_baseball
    - 056_tennis_ball
    - 061_foam_brick # trackable
    - 001_chips_can
    - 021_bleach_cleanser # trackable
    - 023_wine_glass
    - 031_spoon
    - 035_power_drill  # trackable
    - 037_scissors # trackable
    - 044_flat_screwdriver
    - 048_hammer
    - 051_large_clamp # trackable
  conveni:
    # 18
    - clorets
    - koalas_march
    - macademia
    - takenoko
    - coca_cola_300ml
    - calorie_mate_fruit
    - xylitol_freshmint
    - 2nd_cupnoodle  # material binding error
    - golden_curry_chukara
    - stew_cream_box
    - kikkoman_soysauce
    - pepper_steak
    - mastard_tube  # material binding error
    - honwasabi_tube
    - vermont_curry_chukara
    - clinica_quick_wash
    - gum_paste
    - kao_soap
    - nonio_mintpaste

ar-train:
  ycb: 
    # 21
    - 005_tomato_soup_can # trackable
    - 007_tuna_fish_can # trackable
    - 009_gelatin_box # trackable
    - 011_banana # trackable
    - 017_orange
    - 040_large_marker # trackable
    - 055_baseball
    - 056_tennis_ball
    - 061_foam_brick # trackable
    # - 001_chips_can # material error
    - 021_bleach_cleanser # trackable
    # - 023_wine_glass # maaterial error
    - 031_spoon
    - 035_power_drill  # trackable
    - 037_scissors # trackable
    - 044_flat_screwdriver
    - 048_hammer
    - 051_large_clamp # trackable
    # from train
    - 026_sponge
    - 015_peach
    - 024_bowl # trackable
    - 033_spatula
    - 050_medium_clamp
  conveni:
    # 21
    - clorets
    - koalas_march
    # - macademia # material error
    - takenoko
    - coca_cola_300ml
    - calorie_mate_fruit
    - xylitol_freshmint
    - golden_curry_chukara
    - stew_cream_box
    - kikkoman_soysauce
    - pepper_steak
    - honwasabi_tube
    - vermont_curry_chukara
    - clinica_quick_wash
    - gum_paste
    - kao_soap
    - nonio_mintpaste
    # from train
    - cupnoodle_curry    
    - ginger_tube
    - canned_iwashi_kabayaki
    - jif
    - 7i_handsoap
