conveni:
- 'xylitol'
- 'clorets'
- 'toppo'
- 'pocky'
- 'kinokonoyama'
- 'chip_star'
- 'koalas_march'
- 'chocoball'
- 'macademia'
- 'takenoko'
- 'coca_cola_300ml'
- 'gogotea_straight'
- 'oi_ocha_350ml'
- 'calorie_mate_cheese'
- 'calorie_mate_fruit'
- 'xylitol_7assort'
- 'xylitol_freshmint'
# - 'pana_battery_1_2'  # not found
- '2nd_cupnoodle'
- 'creap'
- 'cupnoodle_curry'
- 'golden_curry_chukara'
# - 'canned_tsubugai'  # model not found
- 'ginger_tube'
- 'mastard_tube'
- 'stew_cream_box'
- 'java_curry_chukara'
- 'kikkoman_soysauce_gennenn'
- 'kikkoman_soysauce'
- 'kizami_aojiso_tube'
- 'canned_iwashi_kabayaki'
- 'pan_meat'
- 'pepper_steak'
- 'honwasabi_tube'
- 'vermont_curry_amakuchi'
- 'vermont_curry_chukara'
- 'jif'
- '7i_handsoap'
# - 'biore_bodysoap_mini'  # quality is too bad
- 'clinica_ad_hamigaki'
- 'clinica_advantage'
- 'clinica_quick_wash'
- 'gum_paste'
- 'kao_soap'
# - 'myuzu_kokei'  # model not found
- 'nonio_mintpaste'
- 'nonio_strong_energy'
